config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework_simplejwt.views import TokenRefreshView

from erp_greenwich.auth.api.views import MyTokenObtainPairView
from erp_greenwich.users.views import HomeView, index

schema_view = get_schema_view(
    openapi.Info(
        title="GAE EndUser API",
        default_version="v1",
        description="Greenwich Application Ecosystem end user api documentation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="cuonglieu3256@gmail.com"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    patterns=[
        path("api/", include("config.api_router")),
        path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    ],
)

urlpatterns = [
    path("", index, name="index"),
    path("home/", HomeView.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("erp_greenwich.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        "swagger.json",
        schema_view.without_ui(cache_timeout=0),
        name="enduser_schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="enduser-schema-swagger-ui",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    # Oauth token
    path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("auth/token/", MyTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/", include("config.api_router")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

erp_greenwich/users/urls.py
from django.urls import path

from erp_greenwich.users.views import (
    change_profile,
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("change-profile/", view=change_profile, name="change-profile"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

erp_greenwich/core/models/time_stamp.py
from django.db import models


class DateTimeModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

erp_greenwich/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

erp_greenwich/core/views/base_view.py
from typing import Any, Optional

from django.db import transaction
from django.db.models import Manager
from django.db.models.base import ModelBase
from django.utils.translation import gettext_lazy as _
from oauth2_provider.contrib.rest_framework import OAuth2Authentication
from rest_framework import status
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework.response import Response
from rest_framework.serializers import Serializer
from rest_framework.viewsets import ModelViewSet
from rest_framework_simplejwt.authentication import JWTAuthentication

from erp_greenwich.auth.oauth2_config.permissions.token_with_action import (
    IsAuthenticatedOrJWTTokenPermissionWithAction,
    IsAuthenticatedOrTokenPermissionWithAction,
)
from erp_greenwich.core.response import APIResponse


class BaseViewSet(ModelViewSet):
    authentication_classes = [OAuth2Authentication, JWTAuthentication]
    permission_classes = [
        IsAuthenticatedOrTokenPermissionWithAction,
        IsAuthenticatedOrJWTTokenPermissionWithAction,
    ]
    serializer_class = None
    filter_backends = [SearchFilter, OrderingFilter]
    filterset_fields = []
    ordering_fields = ["pk"]
    serializer_map = {}

    @property
    def get_scopes_with_actions(self):
        return f"{self.basename}:{self.action}"

    @property
    def action_display(self) -> str:
        """Display action name"""
        return self.action.replace("_", " ")

    def get_serializer_class(self):
        """
        Get action's serializer base on `serializer_map`
        :return: Serializer
        """
        return self.serializer_map.get(self.action, self.serializer_class)

    # TODO: create get_serializer_context

    @property
    def viewset_model(self) -> ModelBase:
        return getattr(self.serializer_class, "Meta").model

    @property
    def model_display(self) -> str:
        """Display ViewSet's model name"""
        return self.viewset_model.__name__.lower()

    @property
    def model_manager(self) -> Optional[Manager]:
        """
        Get models managers
        :return: Manager"""
        return getattr(self.viewset_model, "objects", None)

    def get_queryset(self):
        """
        Get models queryset base on Manager
        :return: QuerySet[Model]
        """
        return self.model_manager.all().order_by("-id" "")

    def external_validate(self, **kwargs) -> bool:
        """
        Using for validation before using `is_valid` function for Serializer.
        Define function with format `external_validate_for_<action_name>` to execute validation beHttpResponsefore
        `is_valid` function call.
        It will return boolean and check HttpResponse with `is_valid` value. If all is true then call `save()` function
        :param kwargs:
        :return: bool
        """
        if hasattr(self, f"external_validate_for_{self.action}"):
            result = getattr(self, f"external_validate_for_{self.action}")(**kwargs)
            if isinstance(result, bool):
                return result
            else:
                return True if result else False
        else:
            return True

    def success_response(self, return_obj, message: str = ""):
        """
        Return the success response for API, serialize the return_obj with serializer_class for return data

        :param return_obj:
        :param message: Custom success message
        :return:
        """
        return APIResponse(
            status=status.HTTP_200_OK,
            success=True,
            messages=[
                _(f"{self.action_display} {self.model_display} successfully")
                if not message
                else message
            ],
            data=self.serializer_class(return_obj).data,
        )

    def failure_response(self, message: str = ""):
        """
        Return the failure response for API
        :param message: Custom failure message
        :return:
        """
        return APIResponse(
            status=status.HTTP_400_BAD_REQUEST,
            messages=[
                _(f"Cannot {self.action_display} {self.model_display}")
                if not message
                else message,
            ],
        )

    def notify(self, obj: Any, **kwargs):
        """
        Using to notify for create/update/action
        This function will execute after `.save()` function
        Define function with format `notify_for_<action_name>` to using notification function
        :param obj:
        :param kwargs:
        :return:
        """
        if hasattr(self, f"notify_for_{self.action}"):
            getattr(self, f"notify_for_{self.action}")(obj, **kwargs)

    def perform_create(self, serializer, **kwargs):
        """Just override `perform_create` function with **kwargs"""
        return serializer.save(**kwargs)

    def perform_update(self, serializer, **kwargs):
        """Just override `perform_update` function with **kwargs"""
        return serializer.save(**kwargs)

    def create(self, request, *args, **kwargs):
        """
        Create new object for model. Define Serializer and register at serializer_map
        format {"create": SomeThingSerializer}
        This function will run `.create` function on Serializer
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        data: dict = request.data
        serializer: Serializer = self.get_serializer(data=data)
        external_check = self.external_validate()
        if serializer.is_valid(raise_exception=True) and external_check:
            with transaction.atomic():
                return_obj = self.perform_create(serializer)
            self.notify(return_obj, **kwargs)
            return Response(self.serializer_class(return_obj).data)
        return self.failure_response()

    def update(self, request, *args, **kwargs):
        """
        Create new object for model. Define Serializer and register at serializer_map
        format {"update": SomeThingSerializer}
        This function will run `.update` function on Serializer

        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        data: dict = request.data
        obj: Any = self.get_object()
        serializer: Serializer = self.get_serializer(obj, data=data)
        self.external_validate(**kwargs)
        if serializer.is_valid(raise_exception=True):
            return_obj = self.perform_update(serializer)
            self.notify(return_obj, **kwargs)
            return Response(self.serializer_class(return_obj).data)
        return self.failure_response()

    def create_nested_model(self, request, *args, **kwargs):
        """
        Create a related object with models. Implement this function and
        register {"action_name": SpecificSerializer} at serializer_map to use.
        This function will automatically execute `.create` function in SpecificSerializer

        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        data: dict = request.data
        serializer: Serializer = self.get_serializer(data=data)
        obj: Any = self.get_object()
        self.external_validate(**kwargs)
        if serializer.is_valid(raise_exception=True):
            return_obj = self.perform_create(serializer, obj=obj)
            self.notify(return_obj, **kwargs)
            return Response(self.serializer_class(return_obj).data)
        return self.failure_response()

erp_greenwich/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.response import Response

from ...core.views.base_view import BaseViewSet
from ..tasks import send_new_user_notification
from .serializers import (
    UserCreateSerializer,
    UserInviteSerializer,
    UserSerializer,
    UserUpdateSerializer,
)

User = get_user_model()


class UserViewSet(BaseViewSet):
    serializer_class = UserSerializer
    lookup_field = "id"
    serializer_map = {
        "me": UserSerializer,
        "retrieve": UserSerializer,
        "create": UserCreateSerializer,
        "update": UserUpdateSerializer,
        "invite": UserInviteSerializer,
    }

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

    @staticmethod
    def notify_for_invite(obj: User, **kwargs):
        send_new_user_notification.delay(user_id=obj.id)

    @action(detail=False, methods=["POST"], url_name="invite", url_path="invite")
    def invite(self, request, *args, **kwargs):
        return super().create(request, *args, **kwargs)

erp_greenwich/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import require_http_methods
from django.views.generic import DetailView, RedirectView, TemplateView, UpdateView

from erp_greenwich.users.models import Client

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(
            reverse("users:detail", kwargs={"username": request.user.username})
        )
    return redirect("home/")


class HomeView(TemplateView):
    template_name = "pages/home.html"


@require_http_methods(["POST"])
@login_required
def change_profile(request):
    try:
        user = User.objects.get(pk=request.user.id)
        data = request.POST.dict()
        user.first_name = data.get("first_name")
        user.last_name = data.get("last_name")
        client, created = Client.objects.get_or_create(
            user=user,
            defaults={
                "user": user,
                "address": data.get("address"),
                "city": data.get("city"),
                "country": data.get("country"),
                "postal_code": data.get("postal_code"),
                "about_me": data.get("about_me"),
            },
        )
        if created:
            client.address = data.get("address")
            client.city = data.get("city")
            client.country = data.get("country")
            client.postal_code = data.get("postal_code")
            client.about_me = data.get("about_me")
            client.save()
        user.save()
        messages.success(request, "User info update successfully")
        return HttpResponseRedirect(
            reverse("users:detail", kwargs={"username": request.user.username})
        )
    except User.DoesNotExist:
        messages.error(request, "User info not found")
        return redirect("home/")

erp_greenwich/templates/users/base_auth.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}ERP-GREENWICH{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <meta name="theme-color" content="#000000"/>
  <link
    rel="apple-touch-icon"
    sizes="76x76"
    href="{% static 'images/img/apple-icon.png' %}"
  />
  <link
    rel="stylesheet"
    href="{% static 'fonts/@fortawesome/fontawesome-free/css/all.min.css' %}"
  />
  <link rel="stylesheet" href="{% static 'css/tailwind.css' %}"/>

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  <!-- Le javascript
  ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
    <!-- Bootstrap JS -->
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"
            integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->
    <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script>
    <!-- place project specific Javascript in this file -->
    <script defer src="{% static 'js/project.js' %}"></script>
  {% endblock javascript %}

</head>

<body class="text-blueGray-700 antialiased">


{% include 'pages/index/navbar.html' %}

{% if messages %}
  <section
    class="header relative pt-16 items-center flex max-h-860-px"
  >
    {% for message in messages %}
      <div class="text-white mx-auto my-6 w-4/6 px-12 py-4 border-0 rounded relative  bg-{{ message.tags }}-500">
      <span class="text-xl inline-block mr-5 align-middle">
        <i class="fas fa-bell"></i>
      </span>
        <span class="inline-block align-middle mr-8">
        <b class="capitalize">{{ message }}</b>
      </span>
        <button
          class="absolute bg-transparent text-2xl font-semibold leading-none close-button mt-4 mr-6 outline-none focus:outline-none"
          onclick="closeAlert(event)">
          <span>×</span>
        </button>
      </div>
    {% endfor %}
  </section>

{% endif %}


{% block content %}
{% endblock content %}


{% block modal %}{% endblock modal %}
{% include 'pages/index/footer.html' %}
{% block inline_javascript %}


  <script>
    (function () {
      if (document.getElementById("get-current-year")) {
        document.getElementById(
          "get-current-year"
        ).innerHTML = new Date().getFullYear();
      }
    })();

    /* Function for opning navbar on mobile */
    function toggleNavbar(collapseID) {
      document.getElementById(collapseID).classList.toggle("hidden");
      document.getElementById(collapseID).classList.toggle("block");
    }

    /* Function for dropdowns */
    function openDropdown(event, dropdownID) {
      let element = event.target;
      while (element.nodeName !== "A") {
        element = element.parentNode;
      }
      Popper.createPopper(element, document.getElementById(dropdownID), {
        placement: "bottom-start",
      });
      document.getElementById(dropdownID).classList.toggle("hidden");
      document.getElementById(dropdownID).classList.toggle("block");
    }

    function closeAlert(event) {
      let element = event.target;
      while (element.nodeName !== "BUTTON") {
        element = element.parentNode;
      }
      element.parentNode.parentNode.removeChild(element.parentNode);
    }
  </script>
{% endblock inline_javascript %}
</body>
</html>

erp_greenwich/templates/users/user_detail.html
{% extends "users/base_auth.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
    <main class="profile-page">
      <section class="relative block h-500-px">
        <div
          class="absolute top-0 w-full h-full bg-center bg-cover"
          style="
            background-image: url('https://images.unsplash.com/photo-1499336315816-097655dcfbda?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=2710&amp;q=80');
          "
        >
          <span
            id="blackOverlay"
            class="w-full h-full absolute opacity-50 bg-black"
          ></span>
        </div>
        <div
          class="top-auto bottom-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden h-70-px"
          style="transform: translateZ(0px)"
        >
          <svg
            class="absolute bottom-0 overflow-hidden"
            xmlns="http://www.w3.org/2000/svg"
            preserveAspectRatio="none"
            version="1.1"
            viewBox="0 0 2560 100"
            x="0"
            y="0"
          >
            <polygon
              class="text-blueGray-200 fill-current"
              points="2560 0 2560 100 0 100"
            ></polygon>
          </svg>
        </div>
      </section>
      <section class="relative py-16 bg-blueGray-200">
        <div class="container mx-auto px-4">
          <div
            class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg -mt-64"
          >
            <div class="px-6">
              <div class="flex flex-wrap justify-center">
                <div
                  class="w-full lg:w-3/12 px-4 lg:order-2 flex justify-center"
                >
                  <div class="relative">
                    <img
                      alt="..."
                      src="{{ user.avatar.url }}"
                      class="shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16 max-w-150-px"
                    />
                  </div>
                </div>
                <div
                  class="w-full lg:w-4/12 px-4 lg:order-3 lg:text-right lg:self-center"
                >
                  <div class="py-6 px-3 mt-32 sm:mt-0">
                    <a href="{% url 'users:update' %}"
                      class="bg-pink-500 active:bg-pink-600 uppercase text-white font-bold hover:shadow-md shadow text-xs px-4 py-2 rounded outline-none focus:outline-none sm:mr-2 mb-1 ease-linear transition-all duration-150"
                      role="button"
                    >
                      Update
                    </a>
                  </div>
                </div>
                <div class="w-full lg:w-4/12 px-4 lg:order-1">
                  <div class="flex justify-center py-4 lg:pt-4 pt-8">
                    <div class="mr-4 p-3 text-center">
                      <span
                        class="text-xl font-bold block uppercase tracking-wide text-blueGray-600"
                        >22</span
                      ><span class="text-sm text-blueGray-400">Friends</span>
                    </div>
                    <div class="mr-4 p-3 text-center">
                      <span
                        class="text-xl font-bold block uppercase tracking-wide text-blueGray-600"
                        >10</span
                      ><span class="text-sm text-blueGray-400">Photos</span>
                    </div>
                    <div class="lg:mr-4 p-3 text-center">
                      <span
                        class="text-xl font-bold block uppercase tracking-wide text-blueGray-600"
                        >89</span
                      ><span class="text-sm text-blueGray-400">Comments</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="text-center mt-12">
                <h3
                  class="text-4xl font-semibold leading-normal mb-2 text-blueGray-700 mb-2"
                >
                  {{ object.username }}
                </h3>
                <div
                  class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase"
                >
                  <i
                    class="fas fa-map-marker-alt mr-2 text-lg text-blueGray-400"
                  ></i>
                  {{ object.client.city}}, {{ object.client.country}}
                </div>
                <div class="mb-2 text-blueGray-600 mt-10">
                  <i class="fas fa-briefcase mr-2 text-lg text-blueGray-400"></i
                  >{{ object.role.name}}
                </div>
                <div class="mb-2 text-blueGray-600">
                  <i
                    class="fas fa-university mr-2 text-lg text-blueGray-400"
                  ></i
                  >University of Greenwich
                </div>
              </div>
              <div class="mt-10 py-10 border-t border-blueGray-200 text-center">
                <div class="flex flex-wrap justify-center">
                  <div class="w-full lg:w-9/12 px-4">
                    <p class="mb-4 text-lg leading-relaxed text-blueGray-700">
                      {{ user.client.about_me }}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
{% endblock content %}